### ISSUE TITLE
Thankyou

### ISSUE THREAD

**Issue by stuaxo** [cjolowicz/hypermodern-python#13]
This is fantastic :)

It's certainly interesting to see what these tools can do for a project.

Appreciate minimizing the entry-points by using nox.

**Comment by stuaxo** [comment]
I had some trouble installing pytype, there was a bug in pip 20.0.1 that was fixed in 20.0.2, upgrading pip fixes this:

https://github.com/google/pytype/issues/501

**Comment by cjolowicz** [comment]
You're welcome, and thanks for providing this feedback :)

Sorry you were affected by the pip troubles. I had a notice about this in the pytype section, but removed it when https://github.com/google/pytype/issues/495 got closed.
