### ISSUE TITLE
Something like this for node? 

### ISSUE THREAD

**Issue by patrickwerz** [cjolowicz/hypermodern-python#140]
Hi Claudio, 
I really enjoyed this comprehensive read. You don't find something like this often on the web. Are you aware of a similar introduction for node or even typescript? 
Thank in advance,
Patrick

**Comment by cjolowicz** [comment]
Unfortunately, no I don't. I quite enjoyed https://github.com/verekia/js-stack-from-scratch back in the day, but it hasn't been updated for three years (which is close to eternity in the Javascript world).
