### ISSUE TITLE
Link to Mocking with Pytest section broken

### ISSUE THREAD

**Issue by navneethc** [cjolowicz/hypermodern-python#205]
Page: https://cjolowicz.github.io/posts/hypermodern-python-02-testing/

Clicking on the link titled _Mocking with pytest-mock_ does not do anything. 

It looks like there is a typo in the ID for the link (`"#mocking-with-pytestmock"`) with the one in the corresponding section of the article (`"mocking-with-pytest-mock"`).

**Comment by cjolowicz** [comment]
thanks for reporting 🌯 fixed
