### ISSUE TITLE
Nox session install not working

### ISSUE THREAD

**Issue by accasey** [cjolowicz/hypermodern-python#312]
I have been following along, and I realise the articles are a few years old and `poetry`, `pip` etc. have moved along.

But when the `install_with_constraints` function does the install it seems as though pip doesn't like the constaints file.
Just wondering if this is something anyone else has seen and/or knows a way around?

```bash
$ nox -s black
nox > Running session black
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/black
nox > poetry export --with dev --format=requirements.txt --output=/tmp/tmplk132qu3
nox > python -m pip install --constraint=/tmp/tmplk132qu3 black
nox > Command python -m pip install --constraint=/tmp/tmplk132qu3 black failed with exit code 1:
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
ERROR: Constraints cannot have extras
nox > Session black failed.
```

**Comment by adamblake** [comment]
@accasey I just ran into this issue as well. I changed that function to the following:

```python
def install_with_constraints(session, *args, **kwargs):
    """
    Install with pip, constraining versions to poetry.lock
    """
    with tempfile.NamedTemporaryFile() as requirements:
        session.run(
            "poetry",
            "export",
            "--with=dev",
            "--format=constraints.txt",
            "--without-hashes",
            f"--output={requirements.name}",
            external=True,
        )
        session.install(f"--constraint={requirements.name}", *args, **kwargs)
```

**Comment by accasey** [comment]
@adamblake Thanks for the comment, it looks like you added `--without-hashes` to the run method. 
I will have to give that a try.

**Comment by adamblake** [comment]
@accasey It's actually two things: 

1. change the format to `constraints.txt` rather than `requirements.txt` to take care of the error you had (doesn't output the extras)
2. add `--without-hashes` to take care of an error that came up when I changed the format to constraints

**Comment by accasey** [comment]
Yes I see that now. Thanks again 😊

**Comment by accasey** [comment]
@adamblake I wonder if you have a different version of poetry than I do.
I have version 1.2.1, and with the amended function it now gives the error `Invalid export format: constraints.txt`.

```bash
$ nox -s black
nox > Running session black
nox > Creating virtual environment (virtualenv) using python3.10 in .nox/black
nox > poetry export --with dev --format=constraints.txt --without-hashes --output=/tmp/tmp6y20uyl6

Invalid export format: constraints.txt
nox > Command poetry export --with dev --format=constraints.txt --without-hashes --output=/tmp/tmp6y20uyl6 failed with exit code 1
nox > Session black failed.
```

And, I guess, to be fair the poetry help (and docs) do say that the only requirements.txt is supported.

**Comment by accasey** [comment]
After a bit of experimenting I have gone with the function below. I had a look at the nox docs as well and didn't see any session.install options for --constraint.. But this one is working for me

```python
def install_with_constraints(session: Session, *args: str, **kwargs: Any) -> None:
    """Install packages constrained by Poetry's lock file.

    This function is a wrapper for nox.sessions.Session.install. It
    invokes pip to install packages inside of the session's virtualenv.
    Additionally, pip is passed a constraints file generated from
    Poetry's lock file, to ensure that the packages are pinned to the
    versions specified in poetry.lock. This allows you to manage the
    packages as Poetry development dependencies.

    Arguments:
        session: The Session object.
        args: Command-line arguments for pip.
        kwargs: Additional keyword arguments for Session.install.

    """
    with tempfile.NamedTemporaryFile() as requirements:
        session.run(
            "poetry",
            "export",
            "--with",
            "dev",
            "--format=requirements.txt",
            "--without-hashes",
            f"--output={requirements.name}",
            external=True,
        )
        session.install("-r", f"{requirements.name}", *args, **kwargs)
```

**Comment by mraarone** [comment]
> I have been following along, and I realise the articles are a few years old and `poetry`, `pip` etc. have moved along.
> 
> 
> 
> But when the `install_with_constraints` function does the install it seems as though pip doesn't like the constaints file.
> 
> Just wondering if this is something anyone else has seen and/or knows a way around?
> 
> 
> 
> ```bash
> 
> $ nox -s black
> 
> nox > Running session black
> 
> nox > Creating virtual environment (virtualenv) using python3.10 in .nox/black
> 
> nox > poetry export --with dev --format=requirements.txt --output=/tmp/tmplk132qu3
> 
> nox > python -m pip install --constraint=/tmp/tmplk132qu3 black
> 
> nox > Command python -m pip install --constraint=/tmp/tmplk132qu3 black failed with exit code 1:
> 
> DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement. Discussion can be found at https://github.com/pypa/pip/issues/8210
> 
> ERROR: Constraints cannot have extras
> 
> nox > Session black failed.
> 
> ```

I updated hypermodern with a lot of stuff and included it in mraarone/dsbaseline if you are interested. It has many fixes including this one. Please feel free to star it or share it with attribution, I can't get it out there but it is amazing. I may write an article in Medium about it to contribute to the community and to attribute you and your hyper modern Python work, which is amazing. Huge fan here. Thank you! -- Aaron
