### ISSUE TITLE
Part 4 - something not right

### ISSUE THREAD

**Issue by staticdev** [cjolowicz/hypermodern-python#42]
Hi!

Just a heads up. There is passage in part 4 when talking about flake8-annotations:

> Configure Flake8 to switch on the warnings generated by the plugin (TYP like type):
> 
> # .flake8
> [flake8]
> select = ANN,B,B9,BLK,C,E,F,I,S,W

But the warning prefix for the plugin is ANN not TYP.

Congratulations and thanks again for the amazing work. Hope to read more from you in the future!

**Comment by cjolowicz** [comment]
Hi @staticdev , thank you for the feedback, appreciated :)

flake8-annotations changed their prefix from `TYP` to `ANN` in version 2.0.0, due to a collision with another flake8 plugin.

You should be able to fix this by upgrading flake8-annotations. BTW, as this is a new major release, this means you cannot simply use `poetry update flake8-annotations`. Instead, edit `pyproject.toml` or use the following command

```sh
poetry add --dev "flake8-annotations@^2.0.0"
```

**Comment by staticdev** [comment]
You are right.. is it possible to edit the article in Medium to change TYP to ANN?

Another quick question about this part 4, you mentioned adding some libraries to mypy.ini to avoid import errors. But it wasn't clear to me when should we do that. You just add it to mypy.ini any new third party dependency? Is there a rule of thumb for that?

**Comment by cjolowicz** [comment]
>  is it possible to edit the article in Medium to change TYP to ANN?

Yes. My plan is to thoroughly update the articles once the Cookiecutter for the article series is off the ground. I can't give you a date, but it should happen within the next 1-2 months.

> Another quick question about this part 4, you mentioned adding some libraries to mypy.ini to avoid import errors. But it wasn't clear to me when should we do that. You just add it to mypy.ini any new third party dependency? Is there a rule of thumb for that?

Don't add them to mypy.ini unless mypy produces a warning about missing imports. You can see what the warnings look like by removing mypy.ini and running the mypy session.

**Comment by staticdev** [comment]
> > is it possible to edit the article in Medium to change TYP to ANN?
> 
> Yes. My plan is to thoroughly update the articles once the Cookiecutter for the article series is off the ground. I can't give you a date, but it should happen within the next 1-2 months.
> 
> > Another quick question about this part 4, you mentioned adding some libraries to mypy.ini to avoid import errors. But it wasn't clear to me when should we do that. You just add it to mypy.ini any new third party dependency? Is there a rule of thumb for that?
> 
> Don't add them to mypy.ini unless mypy produces a warning about missing imports. You can see what the warnings look like by removing mypy.ini and running the mypy session.

I am anxious to read your next articles =)

Why not just ignoring this warning for everything??

```ini
[mypy]

ignore_missing_imports = True
```

**Comment by cjolowicz** [comment]
> the strange fact to me is that mypy considers these third-party packages as "unresolved dependencies". And you are using poetry to get all dependencies resolved.

The option name `ignore_missing_imports` is slightly misleading. The packages can be imported, but mypy does not find type information for them.

Resolving the dependencies with Poetry (and installing them) only ensures that the package can be imported, but not that type information is available. That's still up to the package to provide.

**Comment by staticdev** [comment]
@cjolowicz oddly, I tried to add django and django.* to a [package of mine](https://github.com/staticdev/django-sorting-bootstrap/issues/15), but it keeps giving django errors with:
```ini
[mypy]

[nox.*,django,django.*]
ignore_missing_imports = True
```

And the errors stop with:
```ini
[mypy]

ignore_missing_imports = True
```

Any hints?

**Comment by cjolowicz** [comment]
Hey @staticdev

The section name needs to be prefixed by `mypy-`. So in your example, the section needs to look like this:

```ini
[mypy-nox.*,django,django.*]
ignore_missing_imports = True
```

**Comment by staticdev** [comment]
Perfect!! That fixed it =) Thanks again.

**Comment by cjolowicz** [comment]
You're welcome!

**Comment by staticdev** [comment]
When I first read your articles I didn't know pyproject.toml formatting, and I had some trouble with it. And 100% based on your articles I did [this CLI tool to validate TOML](https://github.com/staticdev/toml-validator)!

I had some trouble with e2e though. I had to mock TOML files, I don't think it is a correct approach for e2e.
