### ISSUE TITLE
Questions!

### ISSUE THREAD

**Issue by pawamoy** [cjolowicz/hypermodern-python#85]
I was going to answer here: https://github.com/pyupio/safety/issues/201 but it's a bit off-topic, so here I come!

---

Very interesting, thanks. A few questions to make sure I understand correctly:

- for each "session", nox uses a specific virtualenv (like tox)
- this is why safety is isolated here
- and it uses the constraints feature of pip to make sure to check the right versions, without actually installing them
- do you list nox as a dev dep in pyproject.toml?

I like the approach for the following reasons:
- replacement of Makefile in pure Python
- install only the packages required for a specific task, not the whole dev dep list (great in CI)

But I have doubts about the possible redundancies:
- poetry-managed venv *AND* one venv for each nox session?
- nox sessions (+venvs) *AND* pre-commit hooks?

Could it be possible to use nox in pre-commit, or pre-commit in nox to avoid these?

Anyway, thanks a lot, this is really interesting 🙂

**Comment by cjolowicz** [comment]
Hi @pawamoy :)

> for each "session", nox uses a specific virtualenv (like tox)

yes

> this is why safety is isolated here

yes

> and it uses the constraints feature of pip to make sure to check the right versions, without actually installing them

The constraints file is passed to pip when installing safety. This makes sure that you get the versions of safety and its dependencies (click, requests, etc), that are specified in your poetry.lock.

> do you list nox as a dev dep in pyproject.toml?

No. Nox sessions invoke Poetry, so it would be problematic to add it as a dependency in Poetry. Somebody asked this before, you can read some more details here: https://medium.com/@lfreua/why-did-you-install-nox-via-pip-and-not-via-poetry-as-a-dev-dependecy-834478694282

> poetry-managed venv AND one venv for each nox session?

Nox sessions are isolated environments running a specific tool in an automated way, with only the dependencies required by that tool. For example, you can use Nox in CI, without ever creating a Poetry environment.

By contrast, the Poetry environment contains all the core and development dependencies, and allows you to interact with your package during development. The Poetry environment is also useful for editor integration.

> nox sessions (+venvs) AND pre-commit hooks?
> Could it be possible to use nox in pre-commit, or pre-commit in nox to avoid these?

I'm still looking for the best way to do this. The article shows one way. More recently, I have switched to letting pre-commit manage hooks, without any integration with Nox and Poetry. Only pre-commit itself is tracked as a Poetry dependency, and run in a Nox session. But I'm not entirely happy with this solution either. You can read more about it in an issue in my Cookiecutter project: https://github.com/cjolowicz/cookiecutter-hypermodern-python/issues/316

**Comment by pawamoy** [comment]
Thank you for your quick answer @cjolowicz!

Poetry run/scripts hacks, invoke, tox, nox, Makefile, pre-commit, docker, pyenv, python versions, isolated envs, combinations of all these...

Really, it's a puzzle 😄 !

**Comment by pawamoy** [comment]
I'll close this, thanks again for your answers :slightly_smiling_face:
